name = "veno-menu-hub"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-03"
pages_build_output_dir = ".vercel/output/static"

[vars]
EMAIL_FROM = "noreply@venoapp.com"
EMAIL_FROM_NAME = "Menu Hub"
NEXT_PUBLIC_SUPABASE_URL = "https://rfquwezkkdyvjftveilf.supabase.co"
NEXT_PUBLIC_BASE_URL = "https://www.venoapp.com"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
EMAIL_FROM = "noreply@venoapp.com"
EMAIL_FROM_NAME = "Menu Hub"
NEXT_PUBLIC_SUPABASE_URL = "https://rfquwezkkdyvjftveilf.supabase.co"
NEXT_PUBLIC_BASE_URL = "https://www.venoapp.com"

[env.preview]
compatibility_flags = ["nodejs_compat"]

[env.preview.vars]
EMAIL_FROM = "noreply@venoapp.com"
EMAIL_FROM_NAME = "Menu Hub"
NEXT_PUBLIC_SUPABASE_URL = "https://rfquwezkkdyvjftveilf.supabase.co"
NEXT_PUBLIC_BASE_URL = "https://www.venoapp.com"
